"""Add last_message_at to Session

Revision ID: 3fe16dc64330
Revises: 25e2d2d35f8a
Create Date: 2025-04-11 15:10:59.085070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe16dc64330'
down_revision: Union[str, None] = '25e2d2d35f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'last_message_at')
    # ### end Alembic commands ###
