"""Add reusable openai_assistant_id

Revision ID: 7497800c8aeb
Revises: e90f8913ea0a
Create Date: 2025-04-11 15:36:24.158611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7497800c8aeb'
down_revision: Union[str, None] = 'e90f8913ea0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'openai_assistant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('sessions_openai_assistant_id_key', 'sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sessions_openai_assistant_id_key', 'sessions', ['openai_assistant_id'])
    op.alter_column('sessions', 'openai_assistant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
