"""Add deleted_at field + auto-generate table name

Revision ID: d2dd8d161ac4
Revises: fb1fdedce21f
Create Date: 2025-04-10 23:25:53.174717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2dd8d161ac4'
down_revision: Union[str, None] = 'fb1fdedce21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('sessions', 'deleted_at')
    op.drop_column('logs', 'deleted_at')
    op.drop_column('companies', 'deleted_at')
    # ### end Alembic commands ###
