"""Add OpenAI Assistant ID to Session

Revision ID: e90f8913ea0a
Revises: 3fe16dc64330
Create Date: 2025-04-11 15:34:13.810285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90f8913ea0a'
down_revision: Union[str, None] = '3fe16dc64330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('openai_assistant_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'sessions', ['openai_assistant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_column('sessions', 'openai_assistant_id')
    # ### end Alembic commands ###
